"""Dashboard, analytics and notification endpoints."""

from __future__ import annotations

import uuid

from fastapi import APIRouter, BackgroundTasks, Query, status

from app.api.deps import (
    AnalyticsServiceDep,
    CurrentUserId,
    NotificationServiceDep,
)
from app.schemas.analytics import DashboardResponse, MonthlyAnalytics, WeeklyProgress
from app.schemas.common import ErrorResponse, MessageResponse
from app.schemas.notification import (
    NotificationCounts,
    NotificationCreate,
    NotificationResponse,
)

router = APIRouter(tags=["Dashboard & Analytics"])


@router.get(
    "/analytics/dashboard",
    response_model=DashboardResponse,
    summary="Everything the dashboard needs",
    responses={401: {"model": ErrorResponse}},
)
async def dashboard(
    user_id: CurrentUserId,
    service: AnalyticsServiceDep,
    background: BackgroundTasks,
    days: int = Query(30, ge=7, le=365),
) -> DashboardResponse:
    """Serve the entire dashboard from one request.

    Every KPI tile, chart series and insight arrives together. A dashboard that
    fires a dozen parallel requests is slower, harder to cache, and renders in
    a visibly staggered way.

    Insights are computed by rules over the user's own data rather than
    generated by a language model, so they are deterministic, testable, and can
    never state a number that contradicts the chart beside them.
    """
    result = await service.dashboard(user_id, days)
    return result


@router.get(
    "/analytics/weekly",
    response_model=WeeklyProgress,
    summary="This week's progress",
)
async def weekly_progress(
    user_id: CurrentUserId, service: AnalyticsServiceDep
) -> WeeklyProgress:
    """Monday-to-Sunday rollup with highlights."""
    return await service.weekly_progress(user_id)


@router.get(
    "/analytics/monthly",
    response_model=MonthlyAnalytics,
    summary="Monthly analytics",
)
async def monthly_analytics(
    user_id: CurrentUserId,
    service: AnalyticsServiceDep,
    days: int = Query(30, ge=14, le=365),
) -> MonthlyAnalytics:
    """Long-window trends, symptom frequency and a consistency score.

    Consistency is the share of days with any log at all — in practice the best
    single predictor of whether the analytics are worth reading.
    """
    return await service.monthly(user_id, days)


# ------------------------------------------------------------ notifications
@router.get(
    "/notifications",
    response_model=list[NotificationResponse],
    summary="List notifications",
)
async def list_notifications(
    user_id: CurrentUserId,
    service: NotificationServiceDep,
    unread_only: bool = Query(False),
    limit: int = Query(50, ge=1, le=100),
) -> list[NotificationResponse]:
    """Notifications that are due now — immediate ones plus matured reminders."""
    rows = await service.list(user_id, unread_only=unread_only, limit=limit)
    return [NotificationResponse.model_validate(r) for r in rows]


@router.get(
    "/notifications/counts",
    response_model=NotificationCounts,
    summary="Total and unread counts",
)
async def notification_counts(
    user_id: CurrentUserId, service: NotificationServiceDep
) -> NotificationCounts:
    """Drives the badge on the bell icon."""
    total, unread = await service.counts(user_id)
    return NotificationCounts(total=total, unread=unread)


@router.post(
    "/notifications",
    response_model=NotificationResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a notification or reminder",
)
async def create_notification(
    payload: NotificationCreate,
    user_id: CurrentUserId,
    service: NotificationServiceDep,
) -> NotificationResponse:
    """Create a notification, optionally scheduled for the future.

    Scheduling is a timestamp on the row rather than a separate scheduler
    process: delivery is just ``scheduled_for <= now()``.
    """
    notification = await service.create(user_id, payload)
    return NotificationResponse.model_validate(notification)


@router.post(
    "/notifications/generate",
    response_model=list[NotificationResponse],
    summary="Generate notifications from recent activity",
)
async def generate_notifications(
    user_id: CurrentUserId, service: NotificationServiceDep
) -> list[NotificationResponse]:
    """Derive streak achievements, cycle reminders and priority insights.

    Deduplicated within a 20-hour window, so opening the app repeatedly does
    not produce the same card five times.
    """
    rows = await service.generate_from_activity(user_id)
    return [NotificationResponse.model_validate(r) for r in rows]


@router.post(
    "/notifications/{notification_id}/read",
    response_model=NotificationResponse,
    summary="Mark one as read",
    responses={404: {"model": ErrorResponse}},
)
async def mark_read(
    notification_id: uuid.UUID,
    user_id: CurrentUserId,
    service: NotificationServiceDep,
) -> NotificationResponse:
    notification = await service.mark_read(user_id, notification_id)
    return NotificationResponse.model_validate(notification)


@router.post(
    "/notifications/read-all",
    response_model=MessageResponse,
    summary="Mark all as read",
)
async def mark_all_read(
    user_id: CurrentUserId, service: NotificationServiceDep
) -> MessageResponse:
    count = await service.mark_all_read(user_id)
    return MessageResponse(message=f"Marked {count} notification(s) as read.")


@router.delete(
    "/notifications/{notification_id}",
    response_model=MessageResponse,
    summary="Delete a notification",
)
async def delete_notification(
    notification_id: uuid.UUID,
    user_id: CurrentUserId,
    service: NotificationServiceDep,
) -> MessageResponse:
    await service.delete(user_id, notification_id)
    return MessageResponse(message="Notification deleted.")
