"""Food composition reference used by the Food Analyzer and the Diet Generator.

Values are per 100 g of edible portion and are approximate composite figures
drawn from standard food-composition tables. They are adequate for the coaching
use case — the difference between a 40 GI and an 80 GI meal is what changes
behaviour, not the third significant figure of its fat content.

Glycaemic index is included because it is the single most decision-relevant
number for someone managing insulin resistance, and it is absent from most
consumer calorie databases. Where a food contains negligible carbohydrate the
GI is recorded as 0 rather than left null, since that is its practical effect
on blood glucose.

Coverage is deliberately weighted toward South Asian foods. Nutrition advice
built only on Western staples is useless to a large share of the people this
product is for.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class FoodItem:
    """Per-100g composition for one food."""

    key: str
    name: str
    calories: float
    protein_g: float
    carbs_g: float
    fat_g: float
    fibre_g: float
    glycemic_index: int
    #: Typical single-serving mass, used when no portion is stated.
    typical_grams: float = 100.0
    aliases: list[str] = field(default_factory=list)
    #: 0–100. How well this food supports a PCOS-oriented eating pattern,
    #: weighing glycaemic load, protein density and fibre.
    pcos_score: int = 50
    category: str = "general"


def _f(
    key: str,
    name: str,
    cal: float,
    p: float,
    c: float,
    fat: float,
    fib: float,
    gi: int,
    grams: float,
    score: int,
    category: str,
    *aliases: str,
) -> FoodItem:
    return FoodItem(
        key=key,
        name=name,
        calories=cal,
        protein_g=p,
        carbs_g=c,
        fat_g=fat,
        fibre_g=fib,
        glycemic_index=gi,
        typical_grams=grams,
        aliases=list(aliases),
        pcos_score=score,
        category=category,
    )


FOODS: dict[str, FoodItem] = {
    item.key: item
    for item in [
        # ---------------------------------------------------------- grains --
        _f(
            "white_rice",
            "White rice (cooked)",
            130,
            2.7,
            28.0,
            0.3,
            0.4,
            73,
            150,
            25,
            "grain",
            "rice",
            "steamed rice",
            "plain rice",
            "chawal",
        ),
        _f(
            "brown_rice",
            "Brown rice (cooked)",
            123,
            2.7,
            25.6,
            1.0,
            1.6,
            68,
            150,
            45,
            "grain",
            "brown rice",
        ),
        _f(
            "parboiled_rice",
            "Parboiled rice (cooked)",
            123,
            2.9,
            26.0,
            0.4,
            1.0,
            55,
            150,
            50,
            "grain",
            "parboiled rice",
            "sella rice",
        ),
        _f(
            "roti",
            "Whole-wheat roti",
            297,
            11.0,
            58.0,
            3.5,
            8.0,
            62,
            40,
            55,
            "grain",
            "roti",
            "rotis",
            "chapati",
            "phulka",
            "wheat roti",
        ),
        _f("naan", "Naan", 310, 8.5, 51.0, 8.0, 2.2, 71, 90, 20, "grain", "butter naan"),
        _f(
            "bajra_roti",
            "Bajra (pearl millet) roti",
            294,
            10.5,
            55.0,
            4.5,
            9.5,
            54,
            45,
            72,
            "grain",
            "bajra roti",
            "bajra",
            "pearl millet",
        ),
        _f(
            "ragi",
            "Ragi (finger millet)",
            320,
            7.3,
            66.0,
            1.3,
            11.5,
            55,
            50,
            70,
            "grain",
            "finger millet",
            "nachni",
            "ragi mudde",
        ),
        _f(
            "jowar_roti",
            "Jowar (sorghum) roti",
            285,
            9.5,
            56.0,
            2.8,
            8.8,
            55,
            45,
            70,
            "grain",
            "jowar roti",
            "jowar",
            "sorghum",
        ),
        _f(
            "oats",
            "Rolled oats (cooked)",
            71,
            2.5,
            12.0,
            1.5,
            1.7,
            55,
            200,
            72,
            "grain",
            "oats",
            "oatmeal",
            "porridge",
            "overnight oats",
        ),
        _f(
            "quinoa",
            "Quinoa (cooked)",
            120,
            4.4,
            21.3,
            1.9,
            2.8,
            53,
            150,
            78,
            "grain",
            "quinoa",
        ),
        _f(
            "white_bread",
            "White bread",
            265,
            9.0,
            49.0,
            3.2,
            2.7,
            75,
            50,
            15,
            "grain",
            "bread",
            "toast",
            "white toast",
        ),
        _f(
            "whole_wheat_bread",
            "Whole-wheat bread",
            247,
            13.0,
            41.0,
            3.4,
            7.0,
            51,
            50,
            55,
            "grain",
            "whole wheat bread",
            "wholewheat bread",
            "whole-wheat toast",
            "brown bread",
            "wholemeal bread",
        ),
        _f(
            "poha",
            "Poha (flattened rice, cooked)",
            130,
            2.6,
            27.0,
            2.0,
            1.0,
            68,
            150,
            35,
            "grain",
            "poha",
            "flattened rice",
        ),
        _f(
            "upma",
            "Upma (semolina)",
            155,
            3.8,
            25.0,
            4.5,
            1.6,
            66,
            180,
            38,
            "grain",
            "upma",
            "rava upma",
        ),
        _f("idli", "Idli", 132, 4.5, 26.0, 0.8, 1.2, 60, 80, 48, "grain", "idli", "idly"),
        _f(
            "dosa",
            "Plain dosa",
            168,
            4.0,
            28.0,
            4.5,
            1.5,
            62,
            100,
            42,
            "grain",
            "dosa",
            "masala dosa",
        ),
        _f(
            "pasta",
            "Pasta (cooked)",
            158,
            5.8,
            31.0,
            0.9,
            1.8,
            49,
            150,
            45,
            "grain",
            "pasta",
            "spaghetti",
            "penne",
        ),
        # --------------------------------------------------------- legumes --
        _f(
            "dal",
            "Dal (cooked lentils)",
            116,
            9.0,
            20.0,
            0.4,
            7.9,
            29,
            150,
            88,
            "legume",
            "dal",
            "daal",
            "lentils",
            "toor dal",
            "moong dal",
            "masoor",
        ),
        _f(
            "rajma",
            "Rajma (kidney beans)",
            127,
            8.7,
            22.8,
            0.5,
            6.4,
            24,
            150,
            88,
            "legume",
            "rajma",
            "kidney beans",
        ),
        _f(
            "chana",
            "Chana (chickpeas)",
            164,
            8.9,
            27.4,
            2.6,
            7.6,
            28,
            150,
            88,
            "legume",
            "chana",
            "chickpeas",
            "chole",
            "garbanzo",
        ),
        _f(
            "black_beans",
            "Black beans",
            132,
            8.9,
            23.7,
            0.5,
            8.7,
            30,
            150,
            87,
            "legume",
            "black beans",
        ),
        _f(
            "soy_chunks",
            "Soy chunks (cooked)",
            145,
            18.0,
            12.0,
            1.5,
            6.0,
            20,
            100,
            90,
            "legume",
            "soya chunks",
            "soy",
            "textured vegetable protein",
        ),
        _f(
            "tofu",
            "Tofu",
            76,
            8.1,
            1.9,
            4.8,
            0.3,
            15,
            120,
            90,
            "legume",
            "tofu",
            "bean curd",
        ),
        _f(
            "peanuts",
            "Peanuts",
            567,
            25.8,
            16.1,
            49.2,
            8.5,
            14,
            30,
            70,
            "legume",
            "peanuts",
            "peanut",
            "groundnut",
            "moongphali",
            "peanut butter",
        ),
        # ---------------------------------------------------------- protein --
        _f(
            "egg",
            "Egg (whole)",
            155,
            13.0,
            1.1,
            11.0,
            0.0,
            0,
            50,
            92,
            "protein",
            "eggs",
            "egg",
            "boiled egg",
            "omelette",
            "omelet",
            "scrambled eggs",
        ),
        _f(
            "chicken_breast",
            "Chicken breast (cooked)",
            165,
            31.0,
            0.0,
            3.6,
            0.0,
            0,
            120,
            95,
            "protein",
            "chicken",
            "grilled chicken",
            "chicken breast",
        ),
        _f(
            "chicken_curry",
            "Chicken curry",
            180,
            16.0,
            5.0,
            10.5,
            1.2,
            20,
            200,
            65,
            "protein",
            "chicken curry",
            "butter chicken",
            "chicken masala",
        ),
        _f(
            "fish",
            "Fish (cooked, lean)",
            145,
            24.0,
            0.0,
            5.0,
            0.0,
            0,
            120,
            95,
            "protein",
            "fish",
            "grilled fish",
            "fish curry",
        ),
        _f(
            "salmon", "Salmon", 208, 20.4, 0.0, 13.4, 0.0, 0, 120, 96, "protein", "salmon"
        ),
        _f(
            "paneer",
            "Paneer",
            265,
            18.3,
            3.6,
            20.8,
            0.0,
            27,
            80,
            78,
            "protein",
            "paneer",
            "cottage cheese",
            "palak paneer",
        ),
        _f(
            "greek_yogurt",
            "Greek yoghurt (plain)",
            59,
            10.0,
            3.6,
            0.4,
            0.0,
            11,
            150,
            92,
            "protein",
            "greek yogurt",
            "greek yoghurt",
            "hung curd",
        ),
        _f(
            "curd",
            "Curd / plain yoghurt",
            61,
            3.5,
            4.7,
            3.3,
            0.0,
            14,
            150,
            80,
            "protein",
            "curd",
            "dahi",
            "plain yogurt",
            "plain yoghurt",
            "yogurt",
            "yoghurt",
        ),
        _f(
            "milk",
            "Milk (whole)",
            61,
            3.2,
            4.8,
            3.3,
            0.0,
            39,
            200,
            62,
            "protein",
            "milk",
            "doodh",
        ),
        _f(
            "whey_protein",
            "Whey protein powder",
            400,
            80.0,
            8.0,
            5.0,
            0.0,
            15,
            30,
            85,
            "protein",
            "whey",
            "protein powder",
            "protein shake",
        ),
        # -------------------------------------------------------- vegetables --
        _f(
            "mixed_vegetables",
            "Mixed vegetables (cooked)",
            65,
            2.6,
            10.0,
            1.8,
            3.6,
            32,
            150,
            88,
            "vegetable",
            "sabzi",
            "mixed veg",
            "vegetable curry",
            "vegetables",
            "veggies",
        ),
        _f(
            "spinach",
            "Spinach",
            23,
            2.9,
            3.6,
            0.4,
            2.2,
            15,
            100,
            95,
            "vegetable",
            "spinach",
            "palak",
        ),
        _f(
            "broccoli",
            "Broccoli",
            34,
            2.8,
            6.6,
            0.4,
            2.6,
            15,
            120,
            95,
            "vegetable",
            "broccoli",
        ),
        _f(
            "salad",
            "Green salad (undressed)",
            20,
            1.2,
            3.5,
            0.2,
            1.8,
            15,
            120,
            95,
            "vegetable",
            "salad",
            "green salad",
            "kachumber",
        ),
        _f(
            "potato",
            "Potato (boiled)",
            87,
            1.9,
            20.1,
            0.1,
            1.8,
            78,
            150,
            30,
            "vegetable",
            "potato",
            "aloo",
            "boiled potato",
        ),
        _f(
            "sweet_potato",
            "Sweet potato",
            86,
            1.6,
            20.1,
            0.1,
            3.0,
            63,
            150,
            60,
            "vegetable",
            "sweet potato",
            "shakarkandi",
        ),
        _f(
            "okra",
            "Okra (bhindi)",
            33,
            1.9,
            7.5,
            0.2,
            3.2,
            20,
            120,
            92,
            "vegetable",
            "okra",
            "bhindi",
            "ladies finger",
        ),
        _f(
            "cauliflower",
            "Cauliflower",
            25,
            1.9,
            5.0,
            0.3,
            2.0,
            15,
            120,
            93,
            "vegetable",
            "cauliflower",
            "gobi",
        ),
        # ------------------------------------------------------------ fruit --
        _f(
            "apple",
            "Apple",
            52,
            0.3,
            13.8,
            0.2,
            2.4,
            36,
            180,
            78,
            "fruit",
            "apple",
            "seb",
        ),
        _f(
            "banana",
            "Banana",
            89,
            1.1,
            22.8,
            0.3,
            2.6,
            51,
            120,
            55,
            "fruit",
            "banana",
            "kela",
        ),
        _f(
            "berries",
            "Mixed berries",
            50,
            0.9,
            11.5,
            0.4,
            4.5,
            32,
            100,
            90,
            "fruit",
            "berries",
            "blueberries",
            "strawberries",
            "raspberries",
        ),
        _f(
            "orange",
            "Orange",
            47,
            0.9,
            11.8,
            0.1,
            2.4,
            43,
            150,
            75,
            "fruit",
            "orange",
            "santra",
        ),
        _f(
            "mango",
            "Mango",
            60,
            0.8,
            15.0,
            0.4,
            1.6,
            51,
            150,
            55,
            "fruit",
            "mango",
            "aam",
        ),
        _f(
            "watermelon",
            "Watermelon",
            30,
            0.6,
            7.6,
            0.2,
            0.4,
            72,
            200,
            55,
            "fruit",
            "watermelon",
            "tarbooj",
        ),
        _f(
            "guava",
            "Guava",
            68,
            2.6,
            14.3,
            1.0,
            5.4,
            33,
            150,
            85,
            "fruit",
            "guava",
            "amrud",
        ),
        # ------------------------------------------------------- fats & nuts --
        _f(
            "almonds",
            "Almonds",
            579,
            21.2,
            21.6,
            49.9,
            12.5,
            15,
            28,
            88,
            "fat",
            "almonds",
            "almond",
            "badam",
        ),
        _f(
            "walnuts",
            "Walnuts",
            654,
            15.2,
            13.7,
            65.2,
            6.7,
            15,
            28,
            88,
            "fat",
            "walnuts",
            "walnut",
            "akhrot",
        ),
        _f(
            "olive_oil",
            "Olive oil",
            884,
            0.0,
            0.0,
            100.0,
            0.0,
            0,
            10,
            75,
            "fat",
            "olive oil",
        ),
        _f(
            "ghee",
            "Ghee",
            900,
            0.0,
            0.0,
            100.0,
            0.0,
            0,
            8,
            45,
            "fat",
            "ghee",
            "clarified butter",
        ),
        _f(
            "butter",
            "Butter",
            717,
            0.9,
            0.1,
            81.1,
            0.0,
            0,
            10,
            35,
            "fat",
            "butter",
            "makhan",
        ),
        _f("avocado", "Avocado", 160, 2.0, 8.5, 14.7, 6.7, 15, 100, 90, "fat", "avocado"),
        _f(
            "chia_seeds",
            "Chia seeds",
            486,
            16.5,
            42.1,
            30.7,
            34.4,
            1,
            20,
            92,
            "fat",
            "chia",
            "chia seeds",
        ),
        _f(
            "flax_seeds",
            "Flax seeds",
            534,
            18.3,
            28.9,
            42.2,
            27.3,
            1,
            15,
            92,
            "fat",
            "flaxseed",
            "flax seeds",
            "alsi",
        ),
        # ------------------------------------------------ processed & sweets --
        _f(
            "samosa",
            "Samosa",
            308,
            5.0,
            32.0,
            17.9,
            2.5,
            65,
            60,
            12,
            "processed",
            "samosa",
        ),
        _f(
            "pakora",
            "Pakora",
            315,
            7.0,
            28.0,
            19.0,
            3.5,
            60,
            70,
            18,
            "processed",
            "pakora",
            "bhajji",
            "fritters",
        ),
        _f(
            "french_fries",
            "French fries",
            312,
            3.4,
            41.0,
            15.0,
            3.8,
            75,
            120,
            8,
            "processed",
            "fries",
            "french fries",
            "chips",
        ),
        _f(
            "pizza",
            "Pizza (cheese)",
            266,
            11.0,
            33.0,
            10.0,
            2.3,
            60,
            150,
            15,
            "processed",
            "pizza",
        ),
        _f(
            "burger",
            "Burger",
            295,
            15.0,
            30.0,
            13.0,
            1.8,
            66,
            180,
            15,
            "processed",
            "burger",
            "hamburger",
        ),
        _f(
            "instant_noodles",
            "Instant noodles",
            448,
            9.4,
            60.0,
            18.0,
            2.4,
            73,
            80,
            8,
            "processed",
            "maggi",
            "instant noodles",
            "ramen",
        ),
        _f(
            "gulab_jamun",
            "Gulab jamun",
            380,
            4.5,
            52.0,
            17.0,
            0.5,
            75,
            60,
            5,
            "sweet",
            "gulab jamun",
            "mithai",
        ),
        _f(
            "chocolate",
            "Milk chocolate",
            535,
            7.6,
            59.4,
            29.7,
            3.4,
            45,
            30,
            15,
            "sweet",
            "chocolate",
        ),
        _f(
            "ice_cream",
            "Ice cream",
            207,
            3.5,
            23.6,
            11.0,
            0.7,
            61,
            100,
            12,
            "sweet",
            "ice cream",
        ),
        _f(
            "cake",
            "Sponge cake",
            350,
            5.0,
            52.0,
            14.0,
            0.9,
            67,
            80,
            8,
            "sweet",
            "cake",
            "pastry",
        ),
        _f(
            "biscuit",
            "Sweet biscuit",
            480,
            6.5,
            66.0,
            21.0,
            2.0,
            70,
            30,
            12,
            "sweet",
            "biscuit",
            "cookie",
            "cookies",
        ),
        # ---------------------------------------------------------- drinks --
        _f(
            "tea_with_sugar",
            "Tea with milk and sugar",
            60,
            1.5,
            9.5,
            1.8,
            0.0,
            60,
            200,
            25,
            "drink",
            "chai",
            "tea",
            "milk tea",
        ),
        _f(
            "black_coffee",
            "Black coffee (unsweetened)",
            2,
            0.3,
            0.0,
            0.0,
            0.0,
            0,
            200,
            80,
            "drink",
            "coffee",
            "black coffee",
            "americano",
        ),
        _f(
            "soft_drink",
            "Sugary soft drink",
            42,
            0.0,
            10.6,
            0.0,
            0.0,
            63,
            330,
            3,
            "drink",
            "soda",
            "cola",
            "soft drink",
            "coke",
            "pepsi",
        ),
        _f(
            "fruit_juice",
            "Fruit juice",
            45,
            0.5,
            10.9,
            0.1,
            0.2,
            50,
            250,
            30,
            "drink",
            "juice",
            "orange juice",
            "fruit juice",
        ),
    ]
}

#: Alias → key index, longest alias first so "brown rice" beats "rice".
FOOD_ALIAS_INDEX: list[tuple[str, str]] = sorted(
    (
        (alias.lower(), item.key)
        for item in FOODS.values()
        for alias in [item.name, *item.aliases]
    ),
    key=lambda pair: len(pair[0]),
    reverse=True,
)


def lookup_food(text: str) -> FoodItem | None:
    """Find the best food match in a free-text description."""
    lowered = " ".join(text.lower().split())
    for alias, key in FOOD_ALIAS_INDEX:
        if alias in lowered:
            return FOODS[key]
    return None


def find_all_foods(text: str, limit: int = 8) -> list[FoodItem]:
    """Identify every distinct food mentioned in a description.

    Matched aliases are blanked out as they are consumed so that "chicken
    curry" is not also counted as plain "chicken", which would double the
    protein of the meal.
    """
    remaining = " ".join(text.lower().split())
    found: list[FoodItem] = []
    seen: set[str] = set()

    for alias, key in FOOD_ALIAS_INDEX:
        if len(found) >= limit:
            break
        if key in seen:
            continue
        if alias in remaining:
            found.append(FOODS[key])
            seen.add(key)
            remaining = remaining.replace(alias, " ")
    return found


def healthier_alternatives(item: FoodItem) -> list[FoodItem]:
    """Suggest swaps: same category, materially better PCOS score."""
    return sorted(
        (
            candidate
            for candidate in FOODS.values()
            if candidate.category == item.category
            and candidate.pcos_score >= item.pcos_score + 20
        ),
        key=lambda c: c.pcos_score,
        reverse=True,
    )[:3]


def score_meal(items: list[tuple[FoodItem, float]]) -> tuple[int, str]:
    """Score a whole meal 0–100 for PCOS suitability, with a verdict.

    The score is a gram-weighted mean of each food's own score, then adjusted
    for two whole-meal properties that no single ingredient captures: the
    meal's glycaemic load and whether it contains enough protein to blunt the
    glucose response.
    """
    if not items:
        return 50, "Not enough information to assess this meal."

    total_grams = sum(grams for _, grams in items) or 1.0
    weighted = sum(item.pcos_score * grams for item, grams in items) / total_grams

    total_carbs = sum(item.carbs_g * grams / 100 for item, grams in items)
    total_protein = sum(item.protein_g * grams / 100 for item, grams in items)
    total_fibre = sum(item.fibre_g * grams / 100 for item, grams in items)

    # Glycaemic load = Σ(GI × available carbs) / 100.
    glycemic_load = (
        sum(item.glycemic_index * (item.carbs_g * grams / 100) for item, grams in items)
        / 100
    )

    score = weighted
    if glycemic_load > 20:
        score -= 12
    elif glycemic_load < 10:
        score += 8
    if total_protein >= 20:
        score += 8
    elif total_protein < 8 and total_carbs > 30:
        score -= 10  # a carbohydrate-only meal is the worst pattern here
    if total_fibre >= 8:
        score += 5

    final = int(max(0, min(100, round(score))))

    if final >= 75:
        verdict = "This is a strong choice for managing PCOS."
    elif final >= 55:
        verdict = "A reasonable meal with room for one improvement."
    elif final >= 35:
        verdict = "This is likely to spike your blood sugar — worth adjusting."
    else:
        verdict = "This meal works against insulin sensitivity. An occasional treat is fine; as a regular pattern it is worth changing."

    return final, verdict
