"""Dashboard aggregation, trend analysis and generated insights.

The dashboard is one request, not twelve. Every widget on the page is served
from a single ``/analytics/dashboard`` call, because a dashboard that fires a
dozen parallel requests is slower, harder to cache, and produces a visibly
staggered render.

Insights are **rule-based, computed from the user's own data**, not generated by
a language model. Three reasons: they must be deterministic enough to test, they
must never invent a number that contradicts the chart beside them, and they cost
nothing to produce on every dashboard load.
"""

from __future__ import annotations

import statistics
import uuid
from datetime import date, timedelta

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.repositories.health import (
    CycleRepository,
    PredictionRepository,
    SymptomRepository,
)
from app.repositories.tracking import (
    HabitRepository,
    MealRepository,
    MoodRepository,
    SleepRepository,
    WaterRepository,
    WeightRepository,
    WorkoutRepository,
)
from app.repositories.user import ProfileRepository, UserRepository
from app.schemas.analytics import (
    AIInsight,
    DashboardResponse,
    MetricCard,
    MonthlyAnalytics,
    TimeSeries,
    TrendPoint,
    WeeklyProgress,
)
from app.services.health_service import CycleService
from app.services.tracking_service import HabitService, MealService

logger = get_logger(__name__)

DEFAULT_WINDOW_DAYS = 30


class AnalyticsService:
    def __init__(self, session: AsyncSession) -> None:
        self.session = session
        self.users = UserRepository(session)
        self.profiles = ProfileRepository(session)
        self.cycles = CycleRepository(session)
        self.symptoms = SymptomRepository(session)
        self.predictions = PredictionRepository(session)
        self.meals = MealRepository(session)
        self.workouts = WorkoutRepository(session)
        self.water = WaterRepository(session)
        self.sleep = SleepRepository(session)
        self.weight = WeightRepository(session)
        self.mood = MoodRepository(session)
        self.habits = HabitRepository(session)

    # ------------------------------------------------------------ dashboard
    async def dashboard(
        self, user_id: uuid.UUID, days: int = DEFAULT_WINDOW_DAYS
    ) -> DashboardResponse:
        today = date.today()
        start = today - timedelta(days=days - 1)

        user = await self.users.get(user_id)
        profile = await self.profiles.get_by_user(user_id)

        weight_rows = await self.weight.list_between(user_id, start, today)
        sleep_rows = await self.sleep.list_between(user_id, start, today)
        water_rows = await self.water.list_between(user_id, start, today)
        mood_rows = await self.mood.list_between(user_id, start, today)
        meal_totals = await self.meals.daily_totals(user_id, start, today)
        workout_days = await self.workouts.weekly_minutes(user_id, start, today)

        weight_series = self._series(
            "weight", "kg",
            {row.logged_on: row.weight_kg for row in weight_rows},
            start, today, lower_is_better=True,
        )
        sleep_series = self._series(
            "sleep", "hours",
            {row.logged_on: row.hours for row in sleep_rows}, start, today,
        )
        water_series = self._series(
            "water", "ml",
            {row.logged_on: float(row.millilitres) for row in water_rows},
            start, today,
        )
        mood_series = self._series(
            "mood", "score",
            {row.logged_on: float(row.mood_score) for row in mood_rows},
            start, today,
        )
        calorie_series = self._series(
            "calories", "kcal",
            {row["date"]: row["calories"] for row in meal_totals}, start, today,
        )
        workout_series = self._series(
            "workout_minutes", "minutes",
            {row["date"]: float(row["minutes"]) for row in workout_days},
            start, today,
        )

        habit_service = HabitService(self.session)
        habit_stats = await habit_service.list_with_stats(user_id)

        cycle_insights = await CycleService(self.session).insights(user_id)
        latest_prediction = await self.predictions.latest(user_id)
        nutrition_today = await MealService(self.session).daily_summary(user_id, today)

        macro_split = self._macro_split(meal_totals)
        metrics = self._metric_cards(
            profile, weight_series, sleep_series, water_rows,
            nutrition_today, workout_series, habit_stats, today,
        )

        insights = self._generate_insights(
            weight_series=weight_series,
            sleep_series=sleep_series,
            water_rows=water_rows,
            mood_rows=mood_rows,
            meal_totals=meal_totals,
            workout_days=workout_days,
            habit_stats=habit_stats,
            cycle_insights=cycle_insights,
            nutrition_today=nutrition_today,
            days=days,
        )

        return DashboardResponse(
            generated_at=today,
            greeting=self._greeting(user.full_name if user else "there"),
            metrics=metrics,
            weight_trend=weight_series,
            sleep_trend=sleep_series,
            calorie_trend=calorie_series,
            water_trend=water_series,
            mood_trend=mood_series,
            workout_minutes_trend=workout_series,
            macro_split=macro_split,
            habit_completion=[
                {
                    "name": h["name"],
                    "colour": h["colour"],
                    "icon": h["icon"],
                    "current_streak": h["current_streak"],
                    "completion_rate_30d": h["completion_rate_30d"],
                    "completed_today": h["completed_today"],
                }
                for h in habit_stats
            ],
            cycle_summary={
                "average_length": cycle_insights.average_cycle_length,
                "regularity": cycle_insights.regularity_label,
                "days_until_next": cycle_insights.days_until_next,
                "predicted_next_start": (
                    cycle_insights.predicted_next_start.isoformat()
                    if cycle_insights.predicted_next_start else None
                ),
                "total_cycles": cycle_insights.total_cycles,
                "variability": cycle_insights.cycle_length_std_dev,
            },
            latest_risk=(
                {
                    "risk_score": latest_prediction.risk_score,
                    "risk_percentage": round(latest_prediction.risk_score * 100, 1),
                    "risk_band": latest_prediction.risk_band,
                    "confidence": latest_prediction.confidence,
                    "assessed_at": latest_prediction.created_at.isoformat(),
                }
                if latest_prediction else None
            ),
            insights=insights,
            streaks={h["name"]: h["current_streak"] for h in habit_stats},
        )

    # -------------------------------------------------------------- series
    @staticmethod
    def _series(
        metric: str,
        unit: str,
        values: dict[date, float],
        start: date,
        end: date,
        *,
        lower_is_better: bool = False,
    ) -> TimeSeries:
        """Build a dense, chart-ready series with gaps preserved as nulls.

        Gaps are kept rather than zero-filled: a day with no weight entry is
        *unknown*, not 0 kg, and zero-filling would draw a cliff on the chart
        and poison the average.
        """
        points: list[TrendPoint] = []
        cursor = start
        while cursor <= end:
            points.append(
                TrendPoint(label=cursor.isoformat(), value=values.get(cursor))
            )
            cursor += timedelta(days=1)

        observed = [v for v in values.values() if v is not None]
        average = round(statistics.mean(observed), 1) if observed else None

        change: float | None = None
        direction = "flat"
        if len(observed) >= 2:
            ordered = [values[d] for d in sorted(values)]
            # Compare the first and last thirds rather than single endpoints, so
            # one unusual weigh-in does not define the entire trend.
            third = max(1, len(ordered) // 3)
            first = statistics.mean(ordered[:third])
            last = statistics.mean(ordered[-third:])
            if first != 0:
                change = round((last - first) / abs(first) * 100, 1)
            if abs(last - first) < max(0.01, abs(first) * 0.02):
                direction = "flat"
            else:
                rising = last > first
                # "up" means *improving*, which for weight means falling.
                direction = (
                    "down" if rising == lower_is_better else "up"
                ) if lower_is_better else ("up" if rising else "down")

        return TimeSeries(
            metric=metric, unit=unit, points=points,
            average=average, change_percentage=change, direction=direction,
        )

    @staticmethod
    def _macro_split(meal_totals: list[dict]) -> dict[str, float]:
        """Share of calories from each macronutrient across the window."""
        protein = sum(r["protein_g"] for r in meal_totals)
        carbs = sum(r["carbs_g"] for r in meal_totals)
        fat = sum(r["fat_g"] for r in meal_totals)
        # 4 kcal/g for protein and carbohydrate, 9 kcal/g for fat.
        calories = protein * 4 + carbs * 4 + fat * 9
        if calories <= 0:
            return {"protein": 0.0, "carbs": 0.0, "fat": 0.0}
        return {
            "protein": round(protein * 4 / calories * 100, 1),
            "carbs": round(carbs * 4 / calories * 100, 1),
            "fat": round(fat * 9 / calories * 100, 1),
        }

    def _metric_cards(
        self, profile, weight_series, sleep_series, water_rows,
        nutrition_today, workout_series, habit_stats, today,
    ) -> list[MetricCard]:  # type: ignore[no-untyped-def]
        latest_weight = next(
            (p.value for p in reversed(weight_series.points) if p.value is not None),
            profile.weight_kg if profile else None,
        )
        today_water = next(
            (row for row in water_rows if row.logged_on == today), None
        )
        workout_minutes_week = sum(
            p.value or 0 for p in workout_series.points[-7:]
        )
        habits_done = sum(1 for h in habit_stats if h["completed_today"])

        return [
            MetricCard(
                key="weight", label="Weight", value=latest_weight, unit="kg",
                change_percentage=weight_series.change_percentage,
                direction=weight_series.direction, icon="scale",
            ),
            MetricCard(
                key="bmi", label="BMI",
                value=profile.bmi if profile else None, unit="",
                secondary_label="Category",
                secondary_value=profile.bmi_category if profile else None,
                icon="activity",
            ),
            MetricCard(
                key="sleep", label="Sleep (avg)",
                value=sleep_series.average, unit="hours", goal=8.0,
                progress_percentage=(
                    round(min(100, sleep_series.average / 8 * 100), 1)
                    if sleep_series.average else None
                ),
                direction=sleep_series.direction, icon="moon",
            ),
            MetricCard(
                key="calories", label="Calories today",
                value=nutrition_today.total_calories, unit="kcal",
                goal=nutrition_today.calorie_goal,
                progress_percentage=(
                    round(
                        nutrition_today.total_calories
                        / nutrition_today.calorie_goal * 100, 1
                    ) if nutrition_today.calorie_goal else None
                ),
                icon="flame",
            ),
            MetricCard(
                key="protein", label="Protein today",
                value=nutrition_today.total_protein_g, unit="g",
                goal=nutrition_today.protein_goal_g,
                progress_percentage=(
                    round(
                        nutrition_today.total_protein_g
                        / nutrition_today.protein_goal_g * 100, 1
                    ) if nutrition_today.protein_goal_g else None
                ),
                icon="drumstick",
            ),
            MetricCard(
                key="water", label="Water today",
                value=float(today_water.millilitres) if today_water else 0.0,
                unit="ml",
                goal=float(today_water.goal_millilitres) if today_water else 2500.0,
                progress_percentage=(
                    today_water.goal_percentage if today_water else 0.0
                ),
                icon="droplet",
            ),
            MetricCard(
                key="workouts", label="Active minutes (7d)",
                value=float(workout_minutes_week), unit="minutes", goal=150.0,
                progress_percentage=round(
                    min(100, workout_minutes_week / 150 * 100), 1
                ),
                direction=workout_series.direction, icon="dumbbell",
            ),
            MetricCard(
                key="habits", label="Habits today",
                value=float(habits_done), unit=f"of {len(habit_stats)}",
                progress_percentage=(
                    round(habits_done / len(habit_stats) * 100, 1)
                    if habit_stats else 0.0
                ),
                icon="target",
            ),
        ]

    # ------------------------------------------------------------ insights
    def _generate_insights(
        self, *, weight_series, sleep_series, water_rows, mood_rows,
        meal_totals, workout_days, habit_stats, cycle_insights,
        nutrition_today, days,
    ) -> list[AIInsight]:  # type: ignore[no-untyped-def]
        """Rules over the user's own data, ordered so praise leads."""
        insights: list[AIInsight] = []

        # --- protein ---
        if meal_totals:
            avg_protein = statistics.mean(r["protein_g"] for r in meal_totals)
            if avg_protein < nutrition_today.protein_goal_g * 0.7:
                insights.append(AIInsight(
                    title="Protein is running low",
                    body=(
                        f"You are averaging {avg_protein:.0f}g of protein a day "
                        f"against a target of {nutrition_today.protein_goal_g:.0f}g. "
                        f"Protein steadies blood sugar and keeps you full — adding "
                        f"eggs, curd, dal or paneer to breakfast is usually the "
                        f"easiest place to close the gap."
                    ),
                    category="nutrition", severity="attention",
                    action_label="Plan a meal", action_url="/dashboard/meals",
                ))

        # --- sleep ---
        if sleep_series.average is not None:
            if sleep_series.average < 6.5:
                insights.append(AIInsight(
                    title="Short sleep is working against you",
                    body=(
                        f"Your average over the last {days} days is "
                        f"{sleep_series.average:.1f} hours. Sleep restriction "
                        f"measurably reduces insulin sensitivity, which is the "
                        f"exact mechanism most PCOS management targets. A "
                        f"consistent wake time is the highest-leverage change."
                    ),
                    category="sleep", severity="attention",
                    action_label="Log sleep", action_url="/dashboard/sleep",
                ))
            elif sleep_series.average >= 7.5:
                insights.append(AIInsight(
                    title="Your sleep is genuinely good",
                    body=(
                        f"Averaging {sleep_series.average:.1f} hours puts you in "
                        f"the range associated with better insulin sensitivity "
                        f"and steadier mood. This is worth protecting."
                    ),
                    category="sleep", severity="positive",
                ))

        # --- movement ---
        week_minutes = sum(row["minutes"] for row in workout_days[-7:])
        if week_minutes >= 150:
            insights.append(AIInsight(
                title=f"{week_minutes} active minutes this week",
                body=(
                    "You have met the 150-minute guideline. For PCOS "
                    "specifically, make sure two of those sessions include "
                    "resistance training — muscle is where glucose gets used."
                ),
                category="fitness", severity="positive",
            ))
        elif week_minutes > 0:
            insights.append(AIInsight(
                title="Movement is below target",
                body=(
                    f"You logged {week_minutes} active minutes this week against "
                    f"a 150-minute guideline. Exercise improves insulin "
                    f"sensitivity independently of weight loss, so frequency "
                    f"matters more than intensity — three brisk 30-minute walks "
                    f"would close most of this gap."
                ),
                category="fitness", severity="attention",
                action_label="Generate a plan", action_url="/dashboard/workouts",
            ))

        # --- hydration ---
        if water_rows:
            met_goal = sum(1 for r in water_rows if r.goal_percentage >= 100)
            rate = met_goal / len(water_rows) * 100
            if rate < 50:
                insights.append(AIInsight(
                    title="Hydration is inconsistent",
                    body=(
                        f"You hit your water goal on {met_goal} of "
                        f"{len(water_rows)} logged days. Keeping a filled bottle "
                        f"visible on your desk is the single most effective fix."
                    ),
                    category="hydration", severity="info",
                ))

        # --- cycle ---
        if cycle_insights.total_cycles >= 3:
            if cycle_insights.regularity_label == "Highly irregular":
                insights.append(AIInsight(
                    title="Your cycles vary substantially",
                    body=(
                        f"Across {cycle_insights.total_cycles} logged cycles your "
                        f"length varies by about "
                        f"{cycle_insights.cycle_length_std_dev} days. Variability "
                        f"is exactly the pattern worth showing a clinician — "
                        f"export your log and take it to your next appointment."
                    ),
                    category="cycle", severity="attention",
                    action_label="View cycle data", action_url="/dashboard/cycle",
                ))
            elif cycle_insights.regularity_label == "Regular":
                insights.append(AIInsight(
                    title="Your cycles are tracking regularly",
                    body=(
                        f"Averaging {cycle_insights.average_cycle_length} days "
                        f"with low variability. Keep logging — a consistent "
                        f"record is what makes any future change obvious."
                    ),
                    category="cycle", severity="positive",
                ))

        # --- habits ---
        best = max(habit_stats, key=lambda h: h["current_streak"], default=None)
        if best and best["current_streak"] >= 7:
            insights.append(AIInsight(
                title=f"{best['current_streak']}-day streak on {best['name']}",
                body=(
                    "Consistency at this length is where habits start running "
                    "on autopilot. Protect the streak, and remember the rule "
                    "that matters is never missing twice."
                ),
                category="habits", severity="positive",
            ))

        # --- mood ---
        if len(mood_rows) >= 5:
            avg_mood = statistics.mean(r.mood_score for r in mood_rows)
            avg_stress = statistics.mean(r.stress_level for r in mood_rows)
            if avg_mood <= 2.4 or avg_stress >= 4.0:
                insights.append(AIInsight(
                    title="Your mood logs suggest a hard stretch",
                    body=(
                        "Rates of anxiety and low mood are meaningfully higher in "
                        "PCOS, and it is not something to push through alone. "
                        "Talking to a professional is a reasonable step, and the "
                        "Mental Wellness Coach is here in the meantime."
                    ),
                    category="mental_wellness", severity="attention",
                    action_label="Talk it through", action_url="/chat",
                ))

        if not insights:
            insights.append(AIInsight(
                title="Log a few days to unlock insights",
                body=(
                    "Oviora builds its observations from your own data. Log "
                    "sleep, meals and movement for about a week and this space "
                    "will fill with patterns specific to you."
                ),
                category="onboarding", severity="info",
                action_label="Start logging", action_url="/dashboard",
            ))

        # Positive first: a wall of criticism is how people stop opening an app.
        order = {"positive": 0, "attention": 1, "info": 2}
        insights.sort(key=lambda i: order.get(i.severity, 3))
        return insights[:6]

    @staticmethod
    def _greeting(name: str) -> str:
        from datetime import datetime

        hour = datetime.now().hour
        first = name.split()[0] if name else "there"
        if hour < 12:
            return f"Good morning, {first}"
        if hour < 17:
            return f"Good afternoon, {first}"
        return f"Good evening, {first}"

    # ------------------------------------------------------------- reports
    async def weekly_progress(self, user_id: uuid.UUID) -> WeeklyProgress:
        today = date.today()
        # Week runs Monday to Sunday.
        week_start = today - timedelta(days=today.weekday())
        week_end = week_start + timedelta(days=6)

        workouts = await self.workouts.list_between(user_id, week_start, week_end)
        sleep_avg = await self.sleep.average_hours(user_id, week_start, week_end)
        meal_totals = await self.meals.daily_totals(user_id, week_start, week_end)
        water_rows = await self.water.list_between(user_id, week_start, week_end)
        mood_rows = await self.mood.list_between(user_id, week_start, week_end)
        habit_stats = await HabitService(self.session).list_with_stats(user_id)
        weight_change = await self.weight.change_over(user_id, 7)

        avg_calories = (
            round(statistics.mean(r["calories"] for r in meal_totals), 1)
            if meal_totals else None
        )
        avg_water = (
            round(statistics.mean(r.millilitres for r in water_rows), 1)
            if water_rows else None
        )
        mood_avg = (
            round(statistics.mean(r.mood_score for r in mood_rows), 2)
            if mood_rows else None
        )
        habit_rate = (
            round(statistics.mean(h["completion_rate_30d"] for h in habit_stats), 1)
            if habit_stats else 0.0
        )
        total_minutes = sum(w.duration_minutes for w in workouts)

        highlights: list[str] = []
        if total_minutes >= 150:
            highlights.append(
                f"Hit the 150-minute activity guideline with {total_minutes} minutes."
            )
        if sleep_avg and sleep_avg >= 7:
            highlights.append(f"Averaged {sleep_avg} hours of sleep.")
        if weight_change is not None and weight_change < 0:
            highlights.append(f"Weight down {abs(weight_change)} kg this week.")
        streaks = [h for h in habit_stats if h["current_streak"] >= 5]
        if streaks:
            highlights.append(
                f"Kept {len(streaks)} habit streak(s) alive for five days or more."
            )
        if not highlights:
            highlights.append(
                "A quiet week. One logged workout and one logged meal is enough "
                "to restart the momentum."
            )

        return WeeklyProgress(
            week_start=week_start,
            week_end=week_end,
            workouts_completed=len(workouts),
            workout_minutes=total_minutes,
            average_sleep_hours=sleep_avg,
            average_calories=avg_calories,
            average_water_ml=avg_water,
            habits_completion_rate=habit_rate,
            mood_average=mood_avg,
            weight_change_kg=weight_change,
            highlights=highlights,
        )

    async def monthly(self, user_id: uuid.UUID, days: int = 30) -> MonthlyAnalytics:
        today = date.today()
        start = today - timedelta(days=days - 1)

        weight_rows = await self.weight.list_between(user_id, start, today)
        sleep_rows = await self.sleep.list_between(user_id, start, today)
        mood_rows = await self.mood.list_between(user_id, start, today)
        meal_totals = await self.meals.daily_totals(user_id, start, today)
        workout_days = await self.workouts.weekly_minutes(user_id, start, today)
        symptom_rows = await self.symptoms.frequency_summary(user_id, start, today)
        cycle_insights = await CycleService(self.session).insights(user_id)

        # Consistency = share of days with any log at all. It is the single
        # best predictor of whether a tracking app produces useful analytics.
        tracked_days = {r.logged_on for r in weight_rows}
        tracked_days |= {r.logged_on for r in sleep_rows}
        tracked_days |= {r.logged_on for r in mood_rows}
        tracked_days |= {r["date"] for r in meal_totals}
        tracked_days |= {r["date"] for r in workout_days}

        dashboard_insights = self._generate_insights(
            weight_series=self._series(
                "weight", "kg", {r.logged_on: r.weight_kg for r in weight_rows},
                start, today, lower_is_better=True,
            ),
            sleep_series=self._series(
                "sleep", "hours", {r.logged_on: r.hours for r in sleep_rows},
                start, today,
            ),
            water_rows=await self.water.list_between(user_id, start, today),
            mood_rows=mood_rows,
            meal_totals=meal_totals,
            workout_days=workout_days,
            habit_stats=await HabitService(self.session).list_with_stats(user_id),
            cycle_insights=cycle_insights,
            nutrition_today=await MealService(self.session).daily_summary(user_id, today),
            days=days,
        )

        return MonthlyAnalytics(
            month=today.strftime("%B %Y"),
            days_tracked=len(tracked_days),
            weight_series=self._series(
                "weight", "kg", {r.logged_on: r.weight_kg for r in weight_rows},
                start, today, lower_is_better=True,
            ),
            sleep_series=self._series(
                "sleep", "hours", {r.logged_on: r.hours for r in sleep_rows},
                start, today,
            ),
            calorie_series=self._series(
                "calories", "kcal", {r["date"]: r["calories"] for r in meal_totals},
                start, today,
            ),
            mood_series=self._series(
                "mood", "score",
                {r.logged_on: float(r.mood_score) for r in mood_rows}, start, today,
            ),
            workout_series=self._series(
                "workout_minutes", "minutes",
                {r["date"]: float(r["minutes"]) for r in workout_days}, start, today,
            ),
            symptom_frequency=[
                {
                    "symptom": r["symptom"],
                    "occurrences": r["occurrences"],
                    "average_severity": r["average_severity"],
                }
                for r in symptom_rows
            ],
            cycle_regularity={
                "label": cycle_insights.regularity_label,
                "average_length": cycle_insights.average_cycle_length,
                "std_dev": cycle_insights.cycle_length_std_dev,
                "irregular_count": cycle_insights.irregular_cycle_count,
            },
            macro_averages=self._macro_split(meal_totals),
            consistency_score=round(len(tracked_days) / days * 100, 1),
            insights=dashboard_insights,
        )
